apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-purge
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/robertsmieja/kubectl-purge/releases/download/v0.1.0/kubectl-purge_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-purge"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-purge"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/robertsmieja/kubectl-purge/releases/download/v0.1.0/kubectl-purge_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-purge"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-purge"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/robertsmieja/kubectl-purge/releases/download/v0.1.0/kubectl-purge_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-purge.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-purge.exe"
  shortDescription: A new plugin
  homepage: https://github.com/robertsmieja/kubectl-purge
  caveats: |
    Usage:
      $ kubectl kubectl-purge

    For additional options:
      $ kubectl kubectl-purge --help
      or https://github.com/robertsmieja/kubectl-purge/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
